### ISSUE TITLE
is UFSAC dataset still available?

### ISSUE THREAD

**Issue by brucewlee** [nusnlp/esr#3]
The link provided in the repo is deprecated. Is the mentioned UFSAC dataset the same as Princeton Wordnet Gloss Corpus here? https://wordnetcode.princeton.edu/glosstag.shtml

The stats look a little different, which makes me question if your "With WNGC" setup in Table 2 is using the same data as the other papers that claim a similar setup.

**Comment by sonodasong** [comment]
You can find [UFSAC](https://github.com/getalp/UFSAC) here and download [Version 2.1](https://drive.google.com/file/d/1kwBMIDBTf6heRno9bdLvF-DahSLHIZyV).

Compared to the one we used (downloaded from the deprecated link), this one has some POS tag differences (e.g., ```VBN``` v.s. ```VBD```).
However, since both ```VBN``` and ```VBD``` will be eventually mapped to ```VERB``` in the [code](https://github.com/nusnlp/esr/blob/main/code/esr/dataset/dataset_semcor_wngc.py#L18), using this one to train the model won't differ a lot from the model we provided.

**Comment by brucewlee** [comment]
Thank you for the quick response. But how did you perform ESR on the FEWS dataset, though? The dataset is not based on WordNet, so it would have been difficult to find hypernym relationships.

**Comment by sonodasong** [comment]
Hypernym is not used for ESR on the FEWS dataset. You can check the [code](https://github.com/nusnlp/esr/tree/main/code/fews) for details.

**Comment by brucewlee** [comment]
@sonodasong Yes. Thank you for sharing the great work. Enjoyed reading the paper!
